callback: http://43.200.219.154:8080/api/v1/ai/readme
model: resources/compiled-bloom-1b7-finetuned-readme-500k-steps

prompt:
  separator: "&&&&&&"
  max_total_tokens: 1348
  max_source_code_tokens: 256

generation:
  max_stream: 2
  temperature: 0.92
  pad_to_multiple_of: 8
  max_length: 2048
